export const HOME = '/'
export const RECIPE_LIST = '/receptek'
export const RECIPE_SINGLE = '/recept/:id'
export const RECIPE_EDIT = '/recept-szerkesztes/:id'
export const RECIPE_CREATE = '/uj-recept'
export const RECIPE_FROM_BACKLOG = '/varolista/recept/:id'
export const RECIPE_EDIT_FROM_BACKLOG = '/varolista/recept-szerkesztes/:id'
export const BACKLOG = '/varolista'